"""Occupancy-grid stand-in for `SpotClient`: same surface, no SDK and no robot.

This exists so the offline-to-online path can be exercised without the robot, and because the
offline dataset was generated by these exact dynamics. A warm start whose simulator disagrees with
the data its weights came from is measuring the mismatch, not the transfer, so the integration
below is kept identical to the generator: velocity command scaled by `vel_limits`, a first-order
tracking lag, world-frame integration, and a move rejected outright when it leaves a free cell.

`spot_data/occupancy.npz` carries the grid. It is a 5 cm rasterization of the recorded GraphNav
cloud, occupied where the band floor+0.20..+1.20 m holds at least two returns, with the central
island replaced by the minimum-area rectangle fitted to it and the walked chain carved back out at
the robot half-width. `free` is the part of that grid which is observed, reachable from the walk,
and at least one robot radius clear of an obstacle.

The robot is what the real numbers come from. Anything measured here is a sanity check on the
plumbing and on the warm start, never a benchmark result.
"""
import heapq
import math
import os

import numpy as np

from deploy.spot_client import SpotClient

# Neighbourhood for the goal distance fields: 8-connected, with diagonals costed at sqrt(2).
_NEIGHBOURS = [
    (-1, 0, 1.0), (1, 0, 1.0), (0, -1, 1.0), (0, 1, 1.0),
    (-1, -1, math.sqrt(2.0)), (-1, 1, math.sqrt(2.0)),
    (1, -1, math.sqrt(2.0)), (1, 1, math.sqrt(2.0)),
]


class SimSpotClient(SpotClient):
    """Integrate body-velocity commands in the lab occupancy grid.

    `scale_action` and `unscale_velocity` are inherited: they are pure and import nothing, so the
    action scaling is the same code the robot runs.

    Args:
        occupancy_path: `occupancy.npz` holding `free`, `lo` and `res`.
        waypoint_xy: {waypoint id: (x, y)} in the seed frame, for reset and GraphNav navigation.
        goal_tol: Termination radius, used here only to decide when navigation has arrived.
        tracking_lag: First-order lag on the commanded velocity. 0 tracks instantly.
        start_noise: Standard deviation of the offset applied when resetting onto a waypoint.
        seed: Seeds the reset poses.
    """

    def __init__(
        self,
        occupancy_path,
        waypoint_xy,
        goal_tol=0.5,
        tracking_lag=0.65,
        start_noise=0.15,
        seed=0,
        **kwargs,
    ):
        super().__init__(hostname='sim', **kwargs)
        with np.load(occupancy_path) as grid:
            self.free = grid['free']
            self.lo = grid['lo']
            self.res = float(grid['res'])
        self.ny, self.nx = self.free.shape
        self.waypoint_xy = dict(waypoint_xy)
        self.goal_tol = goal_tol
        self.tracking_lag = tracking_lag
        self.start_noise = start_noise
        self.rng = np.random.RandomState(seed)

        self.pose = [0.0, 0.0, 0.0]
        self.vel = [0.0, 0.0, 0.0]
        self.blocked = False
        self._fields = {}
        self._nav_target = None

    # -- grid ---------------------------------------------------------------------------------

    def _cell(self, x, y):
        # floor, not int: int() truncates toward zero, so a point just left of the grid origin
        # would land on column 0 and read as free.
        return (
            int(np.floor((y - self.lo[1]) / self.res)),
            int(np.floor((x - self.lo[0]) / self.res)),
        )

    def _is_free(self, x, y):
        row, col = self._cell(x, y)
        return 0 <= row < self.ny and 0 <= col < self.nx and bool(self.free[row, col])

    def _walkable(self, row, col, dy, dx):
        """Whether a one-cell step from (row, col) can actually be taken.

        A diagonal between two free cells is refused when either cell it cuts the corner of is an
        obstacle. The robot moves along the straight line between cell centres, so a cut corner is
        a step that ends free but passes through a wall, and it stops dead against it.
        """
        r, c = row + dy, col + dx
        if not (0 <= r < self.ny and 0 <= c < self.nx and self.free[r, c]):
            return False
        if dy and dx:
            return bool(self.free[r, col] and self.free[row, c])
        return True

    def _nearest_free(self, cell):
        """Nearest free cell, searched outward in rings. Waypoints can fall a cell or two off."""
        if self.free[cell]:
            return cell
        for radius in range(1, 20):
            for dy in range(-radius, radius + 1):
                for dx in range(-radius, radius + 1):
                    row, col = cell[0] + dy, cell[1] + dx
                    if 0 <= row < self.ny and 0 <= col < self.nx and self.free[row, col]:
                        return (row, col)
        raise AssertionError(f'no free cell within 20 cells of {cell}')

    def _distance_field(self, waypoint_id):
        """Free-space distance to a waypoint, by Dijkstra over free cells. Cached per waypoint.

        Straight-line descent would drive into the island. This is the same field the offline
        generator followed, so GraphNav-driven seed episodes here look like the offline episodes.
        """
        if waypoint_id in self._fields:
            return self._fields[waypoint_id]

        source = self._nearest_free(self._cell(*self.waypoint_xy[waypoint_id]))
        dist = np.full((self.ny, self.nx), np.inf)
        dist[source] = 0.0
        frontier = [(0.0, source)]
        while frontier:
            d, cell = heapq.heappop(frontier)
            if d > dist[cell]:
                continue
            for dy, dx, weight in _NEIGHBOURS:
                if not self._walkable(cell[0], cell[1], dy, dx):
                    continue
                row, col = cell[0] + dy, cell[1] + dx
                nd = d + weight * self.res
                if nd < dist[row, col]:
                    dist[row, col] = nd
                    heapq.heappush(frontier, (nd, (row, col)))

        self._fields[waypoint_id] = dist
        return dist

    def _descend(self, field, x, y):
        """Unit world-frame direction of steepest descent, or None at a local minimum.

        Adjacent cells only, and no corner cuts. A wider window picks a cell whose field is lower
        but whose straight line crosses an obstacle, and the robot then pushes into that wall every
        step and never moves. Obstacle cells are `inf` in the field, so they never get chosen.
        """
        row, col = self._cell(x, y)
        best, best_value = None, field[row, col] if np.isfinite(field[row, col]) else np.inf
        for dy in (-1, 0, 1):
            for dx in (-1, 0, 1):
                if (dy or dx) and not self._walkable(row, col, dy, dx):
                    continue
                if field[row + dy, col + dx] < best_value:
                    best, best_value = (dx, dy), field[row + dy, col + dx]
        if best is None:
            return None
        direction = np.array(best, dtype=float)
        return direction / np.linalg.norm(direction)

    # -- connection ---------------------------------------------------------------------------

    def connect(self):
        pass

    def upload_graph(self, map_path):
        pass

    def acquire(self):
        pass

    def release(self):
        pass

    # -- action -------------------------------------------------------------------------------

    def send_velocity(self, vx, vy, wz, duration=None):
        """Advance one control period under a commanded body velocity.

        The robot reaches the command over a few periods, so the commanded velocity is filtered
        before it moves anything. A step into a non-free cell is refused and zeroes the linear
        velocity, which is what walking into a wall does to the measured velocity.
        """
        self._nav_target = None
        dt = self.control_period
        command = np.array([vx, vy, wz], dtype=float)
        self.vel = list(self.tracking_lag * np.array(self.vel) + (1.0 - self.tracking_lag) * command)

        x, y, yaw = self.pose
        cos_yaw, sin_yaw = math.cos(yaw), math.sin(yaw)
        next_x = x + (cos_yaw * self.vel[0] - sin_yaw * self.vel[1]) * dt
        next_y = y + (sin_yaw * self.vel[0] + cos_yaw * self.vel[1]) * dt
        self.blocked = not self._is_free(next_x, next_y)
        if self.blocked:
            self.vel[0] = self.vel[1] = 0.0
        else:
            x, y = next_x, next_y
        yaw = (yaw + self.vel[2] * dt + math.pi) % (2.0 * math.pi) - math.pi
        self.pose = [x, y, yaw]

    def stop(self):
        self.vel = [0.0, 0.0, 0.0]
        self.blocked = False

    # -- state --------------------------------------------------------------------------------

    def get_state(self):
        x, y, yaw = self.pose
        nearest = min(
            self.waypoint_xy,
            key=lambda w: math.hypot(x - self.waypoint_xy[w][0], y - self.waypoint_xy[w][1]),
        )
        return dict(
            x=x,
            y=y,
            yaw=yaw,
            vx=self.vel[0],
            vy=self.vel[1],
            wz=self.vel[2],
            localization_waypoint=nearest,
            localization_age=0.0,
            battery=100.0,
            error='',
        )

    # -- GraphNav -----------------------------------------------------------------------------

    def navigate_to(self, waypoint_id, command_duration=5.0):
        """Advance one control period toward a waypoint, following the free-space distance field.

        `SpotMazeEnv.step_graphnav` records the achieved velocity as the action, so this drives
        through `send_velocity` and the recorded action stays consistent with the dynamics.
        """
        direction = self._descend(self._distance_field(waypoint_id), self.pose[0], self.pose[1])
        if direction is None:
            self.stop()
            self._nav_target = waypoint_id
            return 1

        yaw = self.pose[2]
        cos_yaw, sin_yaw = math.cos(yaw), math.sin(yaw)
        forward = cos_yaw * direction[0] + sin_yaw * direction[1]
        lateral = -sin_yaw * direction[0] + cos_yaw * direction[1]
        yaw_error = (math.atan2(direction[1], direction[0]) - yaw + math.pi) % (2.0 * math.pi) - math.pi

        action = np.array([forward, 1.2 * lateral, np.clip(1.5 * yaw_error, -1.0, 1.0)])
        largest = np.abs(action[:2]).max()
        if largest > 1.0:
            action[:2] /= largest
        if self.blocked:
            # Turn in place after a bump. The filtered velocity lags the command by a few periods,
            # so it can still point at the wall after the field has turned away from it; without
            # this the robot pushes into the same cell forever and the episode is dead.
            action[:2] = 0.0
        self.send_velocity(*self.scale_action(action))
        self._nav_target = waypoint_id
        return 1

    def navigation_reached(self):
        if self._nav_target is None:
            return False
        goal_x, goal_y = self.waypoint_xy[self._nav_target]
        return math.hypot(self.pose[0] - goal_x, self.pose[1] - goal_y) <= self.goal_tol

    def navigate_blocking(self, waypoint_id, timeout=180.0):
        """Place the robot on a waypoint with a fresh heading.

        The robot walks back to the start under GraphNav; here it is put there. Reset steps are
        outside the episode either way, and the perturbation matches the start distribution the
        offline episodes were sampled from, which keeps the warm start on-distribution.
        """
        goal_x, goal_y = self.waypoint_xy[waypoint_id]
        for _ in range(100):
            x, y = np.array([goal_x, goal_y]) + self.rng.normal(0.0, self.start_noise, 2)
            if self._is_free(x, y):
                break
        else:
            x, y = self.waypoint_xy[waypoint_id]
        row, col = self._nearest_free(self._cell(x, y))
        if not self._is_free(x, y):
            x, y = self.lo[0] + (col + 0.5) * self.res, self.lo[1] + (row + 0.5) * self.res
        self.pose = [float(x), float(y), float(self.rng.uniform(-math.pi, math.pi))]
        self.vel = [0.0, 0.0, 0.0]
        self.blocked = False
        self._nav_target = None
